gcloud run deploy $SERVICE_NAME \
--region $GOOGLE_CLOUD_LOCATION \
--project $GOOGLE_CLOUD_PROJECT \
--source . \
--allow-unauthenticated \
--set-env-vars="GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT,GOOGLE_CLOUD_LOCATION=$GOOGLE_CLOUD_LOCATION,GOOGLE_GENAI_USE_VERTEXAI=$GOOGLE_GENAI_USE_VERTEXAI,GOOGLE_GEMINI_MODEL=$GOOGLE_GEMINI_MODEL,EXCHANGERATE_API_KEY=$EXCHANGERATE_API_KEY,CODE_INTERPRETER_EXTENSION_NAME=$CODE_INTERPRETER_EXTENSION_NAME" \
--memory 1G 